investigador_task:
  description: >
   Realice una investigación exhaustiva sobre {topic}. Céntrese en:

    1. Conceptos y definiciones clave

    2. Desarrollo histórico y tendencias recientes

    3. Principales desafíos y oportunidades

    4. Aplicaciones o casos prácticos destacados

    5. Perspectivas futuras y posibles desarrollos

    Asegúrese de organizar sus hallazgos en un formato estructurado con secciones claras.
  
  expected_output: >
    Un documento de investigación completo con secciones bien organizadas que abarcan 
    todos los aspectos solicitados de {topic}. Incluye datos, cifras y ejemplos
    específicos cuando sea relevante.
  agent: investigador

analista_task:
  description: >
    Analice los hallazgos de la investigación y elabore un informe completo sobre {topic}.
    Su informe debe:

    1. Comenzar con un resumen ejecutivo

    2. Incluir toda la información clave de la investigación

    3. Ofrecer un análisis profundo de tendencias y patrones

    4. Ofrecer recomendaciones o consideraciones futuras

    5. Tener un formato profesional y de fácil lectura, con encabezados claros
  expected_output: >
    Un informe profesional y pulido sobre {topic} que presente los hallazgos de la investigación 
    con análisis y perspectivas adicionales. El informe debe estar bien estructurado, con un resumen
     ejecutivo, secciones principales y una conclusión.``'
  agent: analista

  context: 
    - investigador_task

  output_file: output/reporte.md